apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: story
  template:
    metadata:
      labels:
        app: story
    spec:
      containers:
        - name: story
          image: taifdev/kub-data:1
          volumeMounts: 
            - mountPath: /app/story # container internal path where this should be mounted. emptyDir should be mounted in within the container in the /app/story directory
              name: story-volume # you can have multiple volumes integrated. that is why we use the name to direct which volume to be used with this path
      volumes: # in the same line as containers. All the containers of that pod will be able to use this volume
        - name: story-volume
          emptyDir: { } # using emptyDir type in its default settings