apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec: 
  capacity:
    storage: 1Gi
  volumeMode: Filesystem # not FileSystem.   it should be Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data
    type: DirectoryOrCreate