apiVersion: v1
kind: Service
metadata: 
  name: story-service
spec: 
  selector:
    app: story
  type: LoadBalancer # you must add this type. otherwise your pods won't be accessible from the outside/browser
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 3000